version: $(VERSION_FROM_BRANCH)
init:
- ps: "$v = [regex]::match($env:APPVEYOR_REPO_BRANCH,'release/(.*)').Groups[1].Value; Write-Host \"On branch $($env:APPVEYOR_REPO_BRANCH)\"; IF($v) { $env:VERSION_FROM_BRANCH = \"$($v).$($env:APPVEYOR_BUILD_NUMBER)\" } else {  $env:VERSION_FROM_BRANCH = \"0.0.$($env:APPVEYOR_BUILD_NUMBER)\" }; Write-Host \"Set version to $($env:VERSION_FROM_BRANCH)\""
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VERSION_FROM_BRANCH)
  assembly_file_version: $(VERSION_FROM_BRANCH)
  assembly_informational_version: $(VERSION_FROM_BRANCH)
build:
  verbosity: normal
artifacts:
- path: src\PostalCodes\bin\*\*.nupkg
  name: NuGet