version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VERSION_FROM_BRANCH)
  assembly_file_version: $(VERSION_FROM_BRANCH)
  assembly_informational_version: $(VERSION_FROM_BRANCH)
before_build:
- ps: "$v = [regex]::match($env:APPVEYOR_REPO_BRANCH,'release/(.*)').Groups[1].Value\nIF($v) {            \n    $env:VERSION_FROM_BRANCH = \"$($v).$($env:APPVEYOR_BUILD_NUMBER)\"\n} else {            \n    $env:VERSION_FROM_BRANCH = \"0.0.$($env:APPVEYOR_BUILD_NUMBER)\"  \n}"
build:
  verbosity: minimal
artifacts:
- path: src\PostalCodes\bin\*\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: DK9YLl9zwAwoGGPvu+Sf25PN9lLuiIUJgJ/hXXfJiTUNr5FVSIDuio5/Ncl2suLY
  skip_symbols: false
  on:
    branch: /release/.*/